version: '3'

services:
  document-qa-bot:
    build: .
    container_name: document-qa-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - DATA_DIR=data
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER:-GEMINI}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL:-claude-3-haiku-20240307}
      - MAX_CHUNK_SIZE=${MAX_CHUNK_SIZE:-500}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-100}
      - NUM_CHUNKS_RETRIEVE=${NUM_CHUNKS_RETRIEVE:-20}
      - NUM_RERANK=${NUM_RERANK:-150}
      - USE_RERANKING=${USE_RERANKING:-1}
      - TZ=UTC